namespace = "GyDX55sFnbr9yCB-mPyXsy4kAUPUY8ftpWX62s6UcnvfIQ=="
local_channels = ['flexlab1/L2']
reference_channels = ['flexlab1/L1']
entity = 'user.ent'
wavemq = '127.0.0.1:4516'
rate = 3 # number of seconds between calls to 'step'
name = 'lpbctest'
spbc = 'spbctest'
