namespace = "GyDX55sFnbr9yCB-mPyXsy4kAUPUY8ftpWX62s6UcnvfIQ=="
wavemq = '127.0.0.1:4516'
name = 'spbc-jasper-1'
entity = 'spbc-jasper-1.ent'
reference_channels = ['uPMU_4/L1','uPMU_4/L2','uPMU_4/L3']
